services:
  - type: web
    name: Rapport-Tool
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
